// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {settings} from '../models';
import {queue} from '../models';
import {ytdlp} from '../models';

export function CancelJob(arg1:string):Promise<void>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetDiskFree(arg1:string):Promise<number>;

export function GetSettings():Promise<settings.Settings>;

export function ListJobs():Promise<Array<queue.Job>>;

export function OpenDownloadDir():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function PauseJob(arg1:string):Promise<void>;

export function PickDownloadDir():Promise<string>;

export function ProbeURL(arg1:string):Promise<ytdlp.MediaInfo>;

export function RemoveJob(arg1:string):Promise<void>;

export function ResumeJob(arg1:string):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function StartDownload(arg1:app.DownloadRequest):Promise<string>;
