// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDiskFree(arg1) {
  return window['go']['main']['App']['GetDiskFree'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListJobs() {
  return window['go']['main']['App']['ListJobs']();
}

export function OpenDownloadDir() {
  return window['go']['main']['App']['OpenDownloadDir']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PauseJob(arg1) {
  return window['go']['main']['App']['PauseJob'](arg1);
}

export function PickDownloadDir() {
  return window['go']['main']['App']['PickDownloadDir']();
}

export function ProbeURL(arg1) {
  return window['go']['main']['App']['ProbeURL'](arg1);
}

export function RemoveJob(arg1) {
  return window['go']['main']['App']['RemoveJob'](arg1);
}

export function ResumeJob(arg1) {
  return window['go']['main']['App']['ResumeJob'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}
